// Abuja locations
export const ABUJA_LOCATIONS = [
  "Maitama",
  "Asokoro",
  "Katampe",
  "Katampe Extention",
  "Wuse",
  "Garki",
  "Jabi",
  "Utako",
  "Central Business District",
  "Gwarinpa",
  "Kubwa",
  "Lugbe",
  "Karu",
  "Nyanya",
  "Mararaba",
  "Wuye",
  "Keffi",
  "Kuje",
  "Abaji",
  "Guzape",
  "Kwali",
  "Karshi",
  "Kurudu",
  "Jikwoyi",
  "Orozo",
  "Karsana",
  "Dakwo",
  "Lokogoma",
  "Galadimawa",
  "Gudu",
  "Durumi",
  "Apo",
  "Gwagwalada",
  "Dutse",
  "Bwari",
  "Suleja",
];

export const PROPERTY_TYPES = [
  "house",
  "apartment",
  "villa",
  "condo",
  "penthouse",
  "duplex",
  "townhouse",
  "studio",
];

export const PRICE_TYPES = ["for sale", "per month", "per year", "per week"];

export const CURRENCIES = ["NGN", "USD", "EUR", "GBP"];

export const STATUS_OPTIONS = ["Available", "Sold"];

export const FEATURED_PROP = [
  {
    id: "featured-all",
    name: "featured",
    checked: false,
    label: "All Properties",
  },
  {
    id: "featured-yes",
    name: "featured",
    checked: false,
    label: "Featured Only",
  },
  {
    id: "featured-no",
    name: "featured",
    checked: false,
    label: "Not Featured",
  },
];

// Common amenities list
export const COMMON_AMENITIES = [
  "Swimming Pool",
  "Gym/Fitness Center",
  "Cinema/Home Theater",
  "Garden/Park",
  "Balcony/Terrace",
  "Air Conditioning",
  "Central Heating",
  "Fireplace",
  "Security System",
  "CCTV",
  "Parking Space",
  "Garage",
  "Elevator",
  "Concierge",
  "24/7 Security",
  "Playground",
  "Tennis Court",
  "Basketball Court",
  "Spa/Sauna",
  "Jacuzzi",
  "Kitchen Island",
  "Walk-in Closet",
  "Study/Office",
  "Laundry Room",
  "Storage Room",
  "Wine Cellar",
  "Home Office",
  "Guest Room",
  "Maid's Quarters",
  "Solar Panels",
  "Backup Generator",
  "Water Tank",
  "Internet/WiFi",
  "Cable TV",
  "Pet Friendly",
  "Wheelchair Accessible",
  "Furnished",
  "Modern Appliances",
  "Hardwood Floors",
  "Marble Countertops",
  "Granite Countertops",
  "Stainless Steel Appliances",
  "Built-in Wardrobes",
  "Bay Windows",
  "Skylights",
  "High Ceilings",
  "Open Floor Plan",
];
