import { Property } from "./types";

export const initialProperties: Omit<Property, "id"> = {
  title: "",
  location: "",
  price: 0,
  currency: "NGN",
  priceType: "",
  bedrooms: 0,
  bathrooms: 0,
  sqft: 0,
  type: "",
  images: [],
  featured: false,
  description: "",
  amenities: [],
  status: "Available",
  liked: false,
  updatedAt: undefined,
  createdAt: undefined,
};

export const initialBlogData = {
  slug: "",
  title: "",
  excerpt: "",
  content: "",
  author: {
    name: "string",
    image: "string",
  },
  readTime: 0,
  category: "",
  featuredImage: "",
  isPublished: false,
  status: undefined,
  tags: [],
  views: 0,
  likes: 0,
  seoScore: 0,
  metaDescription: "",
  metaKeywords: [],
  createdAt: null,
  publishDate: null,
  updatedAt: null,
};
